name: github-spray

on:
  schedule:
  - cron: '*/2 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Delete old repo
      run: |
        curl -s -S -n -XDELETE \
          -H "Authorization: token ${{ secrets.GithubToken }}" \
          "https://api.github.com/repos/leoh0/d"
    - name: Create new repo
      run: |
        curl -s -S -f -n -XPOST \
          -d "{\"name\": \"d\", \"private\": true}" \
          -H "Authorization: token ${{ secrets.GithubToken }}" \
          "https://api.github.com/user/repos"
    - name: Get date
      run: |
        echo "##[set-output name=date;]$(env TZ=Asia/Seoul date '+%x')"
      id: date
    - name: Update repository
      uses: 'leoh0/github-spray-action'
      with:
        user_name: "Eohyung Lee"
        user_email: "liquidnuker@gmail.com"
        github_url: "github.com"
        github_user: "leoh0"
        github_token: "${{ secrets.GithubToken }}"
        github_repository: https://github.com/leoh0/d
        text: ${{ steps.date.outputs.date }}
